### ISSUE TITLE
Minecraft Options button faded out on servers

### ISSUE THREAD

**Issue by 64-Tesseract** [DimiDimit/Custom-LAN#12]
I'm playing on 1.16 with the Mod Menu mod, which adds an extra button to the pause menu. It seems this it messes with the button order and this mod disables the wrong one, because when I'm playing on a server with it I can't access either my options nor the LAN menu.

**Comment by DimiDimit** [comment]
I can't reproduce this... Could you provide a screenshot and a list of the mods you're using?

**Comment by DimiDimit** [comment]
This issue is getting stale... Do you still have this problem?

**Comment by 64-Tesseract** [comment]
Sorry, I ended up just disabling the mod and forgot about it...

Here's a screenshot in a single player world:  
![LAN settings 1](https://user-images.githubusercontent.com/63184095/143797491-adc1bc7d-1828-45ec-a8d2-f5b0a4c1cb9a.png)  
And on a server:  
![LAN settings 0](https://user-images.githubusercontent.com/63184095/143797517-a93189d9-bb84-4db1-913e-abb33a5ce2b7.png)

It's really finnicky to reproduce, I've been adding and removing mods for a while but I can't figure out where exactly the problem is. I got it down to these 9 mods, but if I remove any of them the button becomes pressable...

- Fabric API 0.37.1
- Mod Menu 1.14.12
- OptiFabric 1.11.18 (plus an Optifine jar)
- Carpet 1.4.44
- Offline Skins v1
- Appleskin 2.0.0
- Better Third Person 1.5.0
- Shulker Box Tooltip 2.3.4
- Custom LAN v2.0.0

Very weird. After my experimentation I actually don't think this mod's causing the issue - maybe updating the others will help...

**Comment by DimiDimit** [comment]
Huh, even with these exact mods, I still can't reproduce this...
![Screenshot of the pause menu with the Options button active and Open to LAN button disabled, also showing 8 loaded mods according to Mod Menu](https://user-images.githubusercontent.com/24961444/143852329-bd1a26aa-7f07-4f0c-b939-6fbe8fae98b9.png)

![Screenshot of the mods folder in GNOME Files showing 10 .jar files](https://user-images.githubusercontent.com/24961444/143852858-7028a58c-f16e-434d-9052-c86cff27b50d.png)

*(Minecraft 1.16.5 with Fabric Loader 0.11.7.)*

**Comment by 64-Tesseract** [comment]
I made a new Minecraft 1.16.5 instance with Fabric 0.11.7, and after copying over my mods I still get the issue...  
I noticed you got the Forge version of Appleskin - try redownloading that. I'll download new versions of the other mods though, something may have been fixed

**Comment by 64-Tesseract** [comment]
Welp, I fixed it - it ended up being Mod Menu's fault like I thought at first.  
I just updated it to the lastest version for 1.16.5 and the issue disappeared. I looked around and found something that's _probably_ related: https://github.com/TerraformersMC/ModMenu/issues/254

Thanks for going through the effort of getting those mods, but I posted this issue on the wrong repo 😅  
Guess it serves as a lesson to always update mods...
