### ISSUE TITLE
1.18.2 Update

### ISSUE THREAD

**Issue by juster-0** [DimiDimit/Custom-LAN#15]

**Comment by superloach** [comment]
Any desire to update this to 1.18.2? A basic attempt at bumping the version gives me the following error, as well as 6 warnings.
```java
/home/superloach/prgm/Custom-LAN/src/main/java/com/dimitrodam/customlan/mixin/PlayerManagerMixin.java:41: error: cannot find symbol
    private void init(MinecraftServer server, DynamicRegistryManager.Impl registryManager, WorldSaveHandler saveHandler,
                                                                    ^
  symbol:   class Impl
  location: interface DynamicRegistryManager
```

**Comment by superloach** [comment]
Swapped `DynamicRegistryManager.Impl` for the new `DynamicRegistryManager.ImmutableImpl`, since the previous `Impl` was an immutable one, and it built successfully. Haven't tested too extensively, but it does work!

**Comment by vasilislam** [comment]
How i get the jar file for 1.18.2?

**Comment by vasilislam** [comment]
I tried superloach's brach but crash the game, the mod loads but the game chash when u try to join in a world

**Comment by juster-0** [comment]
> I tried superloach's brach but crash the game, the mod loads but the game chash when u try to join in a world

Try [this](https://github.com/KosmX/Custom-LAN) fork.

**Comment by vasilislam** [comment]
Thank you, worked. Here is a [link](https://cdn.discordapp.com/attachments/954388687574163506/975487249066123304/custom-lan-1.18.2-v2.0.1.jar) if someone want the mod jar file
