### ISSUE TITLE
Custom LAN crashes in 1.19.

### ISSUE THREAD

**Issue by Kichura** [DimiDimit/Custom-LAN#18]
When attempting to load any singleplayer worlds, The safe mode button automatically gets shown but when you try to create new worlds instead; the client will [just crash](https://pastebin.com/raw/282ryyhA).

**Comment by KosmX** [comment]
https://github.com/KosmX/Custom-LAN/releases/tag/v2.0.2  
Try this one :P

**Comment by Kichura** [comment]
> https://github.com/KosmX/Custom-LAN/releases/tag/v2.0.2 Try this one :P

Fixes my problem, thank you!
