### ISSUE TITLE
1.16.1 version crushes game

### ISSUE THREAD

**Issue by ghost** [DimiDimit/Custom-LAN#2]
Crashes when opening the singleplayer
[crash-2021-08-09_17.49.19-client.txt](https://github.com/DimiDimit/Custom-LAN/files/6953453/crash-2021-08-09_17.49.19-client.txt)

**Comment by DimiDimit** [comment]
It seems that just the Fabric API version was wrong. It should work now, and I replaced the `.jar` on all mod distribution platforms.

*(Note for mod makers: If an `include` mod doesn't actually get included in the built `.jar`, clean your project and rebuild, and it should start working as expected.)*

**Comment by ghost** [comment]
ok thanks
