### ISSUE TITLE
"Edit LAN" gets replaced with the player reporting button

### ISSUE THREAD

**Issue by Kichura** [DimiDimit/Custom-LAN#20]
Whenever the no-chat-reporting mod is installed or not iirc, opening the "Edit LAN" button will cause it to re-direct to the player reporting page instead since 1.19.1,

Originally this issue went to [#100](https://github.com/Aizistral-Studios/No-Chat-Reports/issues/100) but decided to re-direct it here to see if it possible to have the two buttons resolved since other dev explained that it isn't their issue.

**Comment by DimiDimit** [comment]
Oops, I forgot that the "Open to LAN" button gets replaced by the "Player Reporting" button when opening to LAN in 1.19.1!
This has no connection with the No Chat Reports mod.
