### ISSUE TITLE
Custom LAN is incompatible with 1.19.4.

### ISSUE THREAD

**Issue by Kichura** [DimiDimit/Custom-LAN#24]
As title says it - However in 1.19.4, The port can now be changed directly in vanilla instead of having to use this mod for it instead.

**Comment by DimiDimit** [comment]
Done!

Changing the port in Vanilla was added back in 1.19.3, when I also updated the mod's description to reflect what its additions over Vanilla are now (good thing I had the foresight to call it “Custom LAN” and not “Custom LAN Port” ;))!
