### ISSUE TITLE
compatibility with Ngrok LAN

### ISSUE THREAD

**Issue by slovinsqui** [DimiDimit/Custom-LAN#28]
So, this mod reaaaaally helps out when used with ESSENTIAL, and simple voice chat, because everytime you open LAN, the port always changes, but with custom LAN, voicechat keeps the same port so there is no need for tweaking the config files everytime 

but I prefer using Ngrok LAN because for some reason is less laggy and buggy than essential, the only downside being the forever changing port, but Custom LAN is not compatible with Ngrok LAN (crashes when opening the OPEN TO LAN menu), and is the most convinient way to use simple voice chat, so finding a way to pair Ngrok with custom lan would be really cool

maybe it doesnt work because of how ports work n stuff but idunno about that stuff, wouldnt hurt to try tho, if it worked with essential, why wouldnt it work with Ngrok

**Comment by DimiDimit** [comment]
ngrok support has been added in Custom LAN 2.3.0, using the new Tunnel button on the Open to LAN screen!
