### ISSUE TITLE
Add Support for Minecraft 1.21

### ISSUE THREAD

**Issue by Atten007** [DimiDimit/Custom-LAN#36]
Hello,

I have a Minecraft World which is currently on Minecraft version 1.21. I want to install this Mod on my world, but unfortunately, the Mod isn‘t currently available for Minecraft 1.21 so I wanted to ask you: Can you please port this Mod to 1.21? This may be very nice!

Greetings,
Atten007 :)

**Comment by Like475** [comment]
Hi, I have the same problem, I would like to have this mod for 1.21.

**Comment by DimiDimit** [comment]
“On time”, as always! Sorry for the delay.
