### ISSUE TITLE
Random shit

### ISSUE THREAD

**Issue by lynrayy** [DimiDimit/Custom-LAN#37]
![image](https://github.com/user-attachments/assets/4865893e-a109-4ba9-b5f6-fa5a15cad645)

**Comment by DimiDimit** [comment]
What combination of Fabric API and Custom LAN do you have installed on the server, and what—on the client (i.e. only Fabric API, only Custom LAN, both, neither)?

**Comment by lynrayy** [comment]
I have already changed my modpack, updated the factory and installed another mod for LAN. I do not wanto delve into this issue, just try to figure out for yourself why your mod causes such STRANGE reasons for kicking players

Only i can remember - it was latest mod version for 1.19.2

**Comment by DimiDimit** [comment]
If Fabric API was installed on the client, but not Custom LAN, then it's probably a duplicate of #32, which still hasn't been fixed unfortunately, otherwise it's a new issue.

**Comment by lynrayy** [comment]
It was intalled. I used modpack https://modrinth.com/modpack/ryan-cliffords-vr-expirence-2/versions

**Comment by DimiDimit** [comment]
Are you sure it was installed on both the server (person who hosts the world) and client (person who joins it)? I installed the modpack and was able to replicate the issue (with the exact same error message), but only if I didn't install Custom LAN on the client, otherwise it works fine.

**Comment by lynrayy** [comment]
Modpack was installed on both 

LAN mod was installed only for me

**Comment by DimiDimit** [comment]
Well, there you go. Closing as a duplicate of #32. Unfortunately, until that is fixed, if the client has Fabric API (Quilted or not), then they *must* have Custom LAN installed as well, even though this mod doesn't do anything on clients.
I was hoping it would have been fixed on the side of Fabric by now, but I guess I'll have to come up with a workaround…

**Comment by 11kaisd11** [comment]
> they _must_ have Custom LAN installed

Stupidest mod i ever met. This is not better than hamachi. Only thing why i installed this mod - to specify port
