### ISSUE TITLE
[BUG] Crashes when pressing escape

### ISSUE THREAD

**Issue by IzeWare** [DimiDimit/Custom-LAN#38]
It crashes when pressing the escape button after opening to lan
[Crash Report](https://github.com/user-attachments/files/16531737/crash-2024-08-07_12.43.59-client.txt)
[Logs](https://github.com/user-attachments/files/16531769/latest.log)

https://github.com/user-attachments/assets/d641e52f-356e-47ef-8b08-5537b925226c

**Comment by DimiDimit** [comment]
It appears to be an incompatibility with Controlify…

**Comment by DimiDimit** [comment]
It appears the issue was actually fixed on Controlify's end by now, but I just made detection more reliable on my end as well, so hey, double fix!
