### ISSUE TITLE
Change LAN settings mid-game (cheats, gamemode, etc)

### ISSUE THREAD

**Issue by t0mtee** [DimiDimit/Custom-LAN#4]

**Comment by DimiDimit** [comment]
I actually already had this idea, but wanted to fix some things up before starting to work on it.
I'll use this as the tracking issue.

**Comment by DimiDimit** [comment]
You can try out [the build with the new commit](https://github.com/DimiDimit/Custom-LAN/suites/3715997972/artifacts/90845378) and tell me about any issues and complaints before it gets released. In the meantime, I'll update the `/publish` command.
