### ISSUE TITLE
Options Menu is gone when hosting

### ISSUE THREAD

**Issue by Lopolin-LP** [DimiDimit/Custom-LAN#41]
why?
![grafik](https://github.com/user-attachments/assets/51d22da1-25ea-4791-aa06-455d04b1d4f3)

**Comment by DimiDimit** [comment]
It's supposed to replace the Player Reporting button rather than the Options one… Which version are you on and what mods do you have?

**Comment by Lopolin-LP** [comment]
In general it's MC 1.21, Fabric API 0.102.0, Fabric Loader 0.16.0 and Custom Lan 2.3.1, as for the other mods I added an excerpt from the logs which hopefully provides enough information
[mods_from_logs.txt](https://github.com/user-attachments/files/17451987/mods_from_logs.txt)

**Comment by DimiDimit** [comment]
Ah, it's because you've set “Game Menu” in Mod Menu's options to “Insert”. As a workaround for now, you can set it to “Replace”.

However I need to find a more reliable way to find the Open to LAN button, because there's issues with other mods as well, such as #38…

**Comment by DimiDimit** [comment]
Alright, I made it find it by text rather than index, which should be more reliable and fix this.
