### ISSUE TITLE
issue with ngrok tunnel

### ISSUE THREAD

**Issue by ImTheTea** [DimiDimit/Custom-LAN#43]
I honestly do not know if this is just something i did wrong, but i ran into this issue and i do not know where i can search for help, so im posting here.

![image](https://github.com/user-attachments/assets/370d70fd-6a86-487e-8f50-3087a1566153)

tcp-8080-d566875a-6fd1-4add-8876-b4f68eb1a40f

**Comment by DimiDimit** [comment]
Huh, this is quite peculiar… Logs?

**Comment by ImTheTea** [comment]
[2024-11-14-6.log](https://github.com/user-attachments/files/17756789/2024-11-14-6.log)

**Comment by DimiDimit** [comment]
Oh.
> ```
> [11:56:54] [Render thread/INFO]: [STDERR]: Caused by: com.github.alexdlaird.http.HttpClientException: An error occurred when performing the operation (502):{"error_code":103,"status_code":502,"msg":"failed to start tunnel","details":{"err":"failed to start tunnel: You must add a credit or debit card before you can use TCP endpoints on a free account. We require a valid card as a way to combat abuse and keep the internet a safe place. This card will NOT  be charged.\nAdd a card to your account here: https://dashboard.ngrok.com/settings#id-verification\r\n\r\nERR_NGROK_8013\r\n"}}
> ```
Apparently, since June [ngrok accounts require a valid payment method to use TCP endpoints](https://ngrok.com/blog-post/tcp-endpoints-require-verification) in order to reduce spam (it is still free, you will ***not*** be charged)… Fun.

Additionally, I'm seeing this:
> ```
> [11:58:20] [Render thread/INFO]: [STDERR]: com.github.alexdlaird.exception.NgrokException: The ngrok process errored on start: authentication failed: Your account is limited to 1 simultaneous ngrok agent sessions.nYou can run multiple simultaneous tunnels from a single agent session by defining the tunnels in your agent configuration file and starting them with the command `ngrok start --all`.nRead more about the agent configuration file: https://ngrok.com/docs/secure-tunnels/ngrok-agent/reference/confignYou can view your current agent sessions in the dashboard:nhttps://dashboard.ngrok.com/agentsrnrnERR_NGROK_108rn.
> ```
Do you have another instance of Minecraft with Custom LAN running? Though this might not be relevant and may be just a consequence of the first problem, so solve that first.

**Comment by ImTheTea** [comment]
Oh, i just followed a basic tutorial, did not know about the card thing, and the second one by just recreating the instance on ngrok the problem was solved. im going to see if adding the card solves everything, thank you.

**Comment by ImTheTea** [comment]
It seems to have solved the problem, everything working.

**Comment by DimiDimit** [comment]
Nice!
