### ISSUE TITLE
Add ability to control who can use cheats.

### ISSUE THREAD

**Issue by juster-0** [DimiDimit/Custom-LAN#5]

**Comment by DimiDimit** [comment]
You can try out [the build with the new commit](https://github.com/DimiDimit/Custom-LAN/suites/3715997972/artifacts/90845378) and tell me about any issues and complaints before it gets released. In the meantime, I'll update the `/publish` command.

**Comment by juster-0** [comment]
Sorry for late answer. Maybe also add ability to list all ops?

**Comment by DimiDimit** [comment]
I thought that wouldn't be necessary as the `/deop` command suggests the operators (and `/op` suggests the non-operators), however only the owner (and operators with level `3` or higher) can use these. Should normal players be able to find out who is and isn't an operator (an indicator in the `/list` command perhaps)? They can't in a Vanilla dedicated server.

**Comment by juster-0** [comment]
I think nope. But I think that's better to have more obvious way to get ops list (maybe even just `/op` command or `/ops`). "Simple is better than complex", but anyway it's up to you.
